### ISSUE TITLE
Transfer Unit from IDB to Units in BCP package

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/bcpIntermediateDatabase#40]
As a user of the tool bcpIntermediateDatabase/IDB.Tranfer.BCP I want that values that I have put into the column 'Unit' in the table 'Items' of the IDB are transferred to the property 'Units' for items in the ItemsWrapper.xml.
Currently all 'Units' are set to 'each'.

**Comment by kieninj** [comment]
Solved in version 1.0.8:
To support custom unit definitions the user of this tool has to do the following steps:

1. Define own units in configuration of the target Vault
1. Run BCP Export of target Vault
   1. This produces a `UOMwrapper.xml` in the exported BCP package and contains own unit definitions
1. Copy this file to the folder of the IDB tool (location of `bcpIntermediateDatabaseApp.exe`)
1. Create BCP package with IDB tool and as always check log-file for errors. If none:
   1. The BCP package should now have the custom `UOMwrapper.xml` file
   1. The `<bomLink>` items should now have the correct `UofMID` value instead of 1 (Each)

**Comment by kieninj** [comment]
"Units" in ItemIteration also has to be set
