### ISSUE TITLE
IDB.Analyzer.Inventor error “Violation of PRIMARY KEY constraint 'PK_FileFileRelations' .... duplicate key..."

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/bcpIntermediateDatabase#51]
Current situation: When an IDW has a refernce to an assembly AND IPT, The IPT is also referenced in the IAM. 
IDB.Analyzer.Inventor stops with an error message: “Violation of PRIMARY KEY constraint 'PK_FileFileRelations'. Cannot insert duplicate key in object 'dbo.FileFileRelations'. The duplicate key value is (<FileID of IDW>, <FileID of IAM>).”
You can reproduce the issue with the attached IDW, IAM and IPTs of the attached IDWwithIAMcausingStop.ZIP.
Expected result: The IPT is inserted as a ChildID in the 'FileFileRelations' table with ParentID for the IDW and for the IAM. The tool then continues with the other entries.

[IDWwithIAMcausingStop.zip](https://github.com/coolOrangeLabs/bcpIntermediateDatabase/files/5893839/IDWwithIAMcausingStop.zip)

**Comment by kieninj** [comment]
@MarkusCool 
The reason for this problem is not the IPT in the drawing. If that would be the case we would have seen this problem before.

Analysis:
When using LOD's in drawings, the IDW has actually two references to the same IAM. 

<img width="524" alt="Bildschirmfoto 2021-02-05 um 14 12 15" src="https://user-images.githubusercontent.com/34063457/107040108-0ed22680-67bf-11eb-9af0-c30df3b78388.png">

This situation has not been handled yet, but is easy to solve :-)
